# Kernel compile workflow for personal usage
# By Sarthak Roy (sarthakroy2002@gmail.com)

name: Lets Do it

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true   

env:
  TZ: Asia/Kolkata
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ secrets.TOKEN }}
  chat_id: ${{ secrets.CHAT_ID }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:



      - name: Initializing environment
        run: |
          git config --global user.name "Mnml"
          git config --global user.email "edith.brownie•For6785"
          sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch



      - name: Magick Starts Here
        run: |
          git clone $REPO -b $BRANCH kernel 
          cd kernel 
          wget  https://gitlab.com/No1really/ThunderstormReborn-RM6785/-/raw/Reborn-BT/build.sh
          bash build.sh
